# Generated by Django 2.2.5 on 2020-12-29 17:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(choices=[(1, 'Positive'), (0, 'Negative'), (2, 'Recovered'), (3, 'Unknown')], default=1)),
                ('latitude', models.DecimalField(decimal_places=5, max_digits=7)),
                ('longitude', models.DecimalField(decimal_places=5, max_digits=8)),
                ('address', models.CharField(max_length=512)),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
