# Generated by Django 2.2.5 on 2021-04-19 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='municipality',
            field=models.CharField(default='Unknown', max_length=256),
        ),
    ]
